version: "3.9"
services:
  redis:
    container_name: "redis_ru202"
    image: "redis:7.0.8"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redisdata:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redisinsight:
    container_name: "insight"
    image: "redislabs/redisinsight:ri-trusted-origins"
    ports:
      - "8001:8001"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure